export const secretSantaMapping = {
  "Quentin": "Clémence",
  "Rémy": "Michel",
  "Roxane": "Carole",
  "Olivier": "Charlotte",
  "Virginie": "Hugo",
  "Marc": "Nicolas",
  "Florence": "Papy Pierre",
  "Charlotte": "Roxane",
  "Thomas": "Clara",
  "Delphine": "Margaux",
  "Baptiste": "Mathias",
  "Clémence": "Mamychèle",
  "Mamychèle": "Elise",
  "Papy Pierre": "Florence",
  "Nicolas": "Julien",
  "Alexandra": "Marc",
  "Clara": "Olivier",
  "Hugo": "Baptiste",
  "Carole": "Delphine",
  "Michel": "Alexandra",
  "Margaux": "Virginie",
  "Mathias": "Rémy",
  "Julien": "Thomas",
  "Elise": "Quentin"
};