export const secretSantaMapping = {
  "Quentin": "Roxane",
  "Rémy": "Margaux",
  "Roxane": "Thomas",
  "Olivier": "Quentin",
  "Virginie": "Delphine",
  "Marc": "Baptiste",
  "Florence": "Hugo",
  "Charlotte": "Olivier",
  "Thomas": "Florence",
  "Delphine": "Clémence",
  "Baptiste": "Michel",
  "Clémence": "Elise",
  "Mamychèle": "Nicolas",
  "Papy Pierre": "Carole",
  "Nicolas": "Papy Pierre",
  "Alexandra": "Clara",
  "Clara": "Rémy",
  "Hugo": "Mamychèle",
  "Carole": "Virginie",
  "Michel": "Julien",
  "Margaux": "Mathias",
  "Mathias": "Charlotte",
  "Julien": "Alexandra",
  "Elise": "Marc"
};